name: Informationplus
version: 1.0
main: me.georgeawp.informationplus.Informationplus
api-version: 1.13
authors: [ GeorgeAWP ]
description: A simple command which will allow you to see your servers important links, rules and help.

commands:
  server:
    description: Shows the list of commands
    usage: /<command>
