name: Informationplus
version: 1.2
main: me.georgeawp.informationplus.Informationplus
api-version: 1.13
authors: [ GeorgeAWP ]
description: A simple command which will allow you to see your servers important links, rules and help.

commands:
  informationplus:
    description: The main command to view plugin info
    usage: /<command>

  rules:
    description: Rules command.
    usage: /<command>

  links:
    description: Links command
    usage: /<command>

  help:
    description: Help command
    usage: /<command>